export const CHANGE_VIEW_STATE = 'CHANGE_VIEW_STATE';
export const SET_WALLPAPER = 'SET_WALLPAPER';
export const SET_WALLPAPER_LIST = 'SET_WALLPAPER_LIST';
export const CHANGE_FONT_COLOR = 'CHANGE_FONT-COLOR';
export const SET_CURRENT_SKIN_ID = 'SET_CHRRENT_SKIN_ID';
export const SET_LOADING_SKIN_ID = 'SET_LOADING_SKIN_ID';
export const SET_SKIN_TYPE_ID = 'SET_SKIN_TYPE_ID';
export const SET_INDIVIDUATION_DATA = 'SET_INDIVIDUATION_DATA';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SEARCH_ENGINE = 'SET_SEARCH_ENGINE';
export const SET_SEARCH_ENGINE_LIST = 'SET_SEARCH_ENGINE_LIST';
export const SET_SEARCH_ENGINE_LIST_VERSION = 'SET_SEARCH_ENGINE_LIST_VERSION';
export const SET_HOTWORDS_LIST = 'SET_HOTWORDS_LIST';
export const SET_IS_SHOW_SEARCH_ENGINE_LIST = 'SET_IS_SHOW_SEARCH_ENGINE_LIST';

export const SET_IS_SHOW_SIDEBAR = 'SET_IS_SHOW_SIDEBAR';